//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RTO_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string M_Number { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string pas_reset_que { get; set; }
        public Nullable<int> UserTyped { get; set; }
        public string pas_reset_ans { get; set; }
        public string IsActive { get; set; }
        public Nullable<int> FailCount { get; set; }
    
        public virtual UserRole UserRole { get; set; }
    }
}
